version: '3'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=todo_db
      - POSTGRES_USER=todo_user
      - POSTGRES_PASSWORD=todo_password

  api:
    build:
      context: ./backend
    container_name: django
    environment:
      - DEBUG=True
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/code/
    depends_on:
      - db
    command: >
      sh -c "
      cd /code && \
      if [ ! -f manage.py ]; then \
        django-admin startproject backend .; \
      fi && \
      python manage.py migrate && \
      python manage.py runserver 0.0.0.0:8000
      "

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api

volumes:
  postgres_data:
